-- Generated by nwg-displays on 2026-07-06 at 08:54:14. Do not edit manually.

hl.monitor({
    output = "LVDS-1",
    mode = "1366x768@60.02",
    position = "1366x0",
    scale = 1.0
})
hl.monitor({
    output = "VGA-1",
    mode = "1366x768@59.79",
    position = "0x0",
    scale = 1.0,
    mirror = "LVDS-1"
})
