#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┃┫ ┃ ┃  ┃ ┗┫
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┛┻ ┻  ┻ ┗┛
#

# Core Colors
background            #13140d
foreground            #e4e3d7
selection_foreground  #dcea97
selection_background  #414c08
cursor                #c0ce7e
cursor_text_color     #13140d

# Regular Colors
color0  #13140d
color1  #ffb4ab
color2  #c0ce7e
color3  #c5c9a8
color4  #a1d0c4
color5  #214e45
color6  #45492f
color7  #e4e3d7

# Bright Colors
color8  #919283
color9  #93000a
color10 #dcea97
color11 #e1e6c3
color12 #bdecdf
color13 #a1d0c4
color14 #c5c9a8
color15 #e4e3d7
