#  ┏┓┳┳┏┳┓┏┓┏┓┏┳┓┏┓┳┓┏┳┓
#  ┣┫┃┃ ┃ ┃┃┗┓ ┃ ┣┫┣┫ ┃ 
#  ┛┗┗┛ ┻ ┗┛┗┛ ┻ ┛┗┛┗ ┻ 
#                       

#-------------bar, wallpaper & notification daemon--------------#
#---------------------------------------------------------------#
exec-once = killall -q awww-daemon; sleep .5 && awww-daemon
exec-once = killall -q waybar;sleep .5 && waybar
exec-once = killall -q swaync;sleep .5 && swaync
exec-once = hypridle

#--------------applets---------------#
#------------------------------------#
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = swayosd-server

#--------------clipboard history---------------#
#-----------------------------------------------#
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
