#  ┓ ┏┳┳┓┳┓┏┓┓ ┏  ┳┓┳┳┓ ┏┓┏┓
#  ┃┃┃┃┃┃┃┃┃┃┃┃┃  ┣┫┃┃┃ ┣ ┗┓
#  ┗┻┛┻┛┗┻┛┗┛┗┻┛  ┛┗┗┛┗┛┗┛┗┛

# states
windowrule = suppress_event maximize, match:class .*
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float on, match:class ^(nwg-look)$
windowrule = float on, match:class ^(thunar)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(imv)$
windowrule = float on, match:class ^(mpv)$
windowrule = float on, match:class ^(file-roller)$

# opacity
windowrule = opacity 0.9 0.7, match:class ^([Ll]ibreWolf|[Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr)$
windowrule = opacity 0.9 0.7, match:class ^(thunar)$
windowrule = opacity 0.9 0.7, match:class ^(blueman-manager)$
windowrule = opacity 0.9 0.7, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = opacity 0.9 0.7, match:class ^(nwg-look)$
windowrule = opacity 1.0 0.7, match:class ^(kitty)$
windowrule = opacity 0.9 0.7, match:class ^(mpv)$
windowrule = opacity 0.9 0.7, match:class ^(file-roller)$

# sizes
windowrule = size 1000 600, match:class ^(thunar)$
windowrule = size 689 400, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = size 600 500, match:class ^(blueman-manager)$
windowrule = size 800 500, match:class ^(imv)$
windowrule = size 800 500, match:class ^(mpv)$
windowrule = size 800 600, match:class ^(file-roller)$

# picture in picture
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$
windowrule = move 72.5% 70%, match:title ^(Picture-in-Picture)$
windowrule = size 520 320, match:title ^(Picture-in-Picture)$

# special kitty windows
windowrule = float on, match:title ^(PacUpdate)$
windowrule = center on, match:title ^(PacUpdate)$
windowrule = size 800 600, match:title ^(PacUpdate)$
windowrule = float on, match:title ^(KittyNmtui)$
windowrule = center on, match:title ^(KittyNmtui)$
windowrule = size 600 500, match:title ^(KittyNmtui)$

# layer rules
layerrule = blur on, ignore_alpha 0.5, match:namespace waybar
layerrule = blur on, ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = blur on, ignore_alpha 0.5, match:namespace swaync-notification-window
layerrule = blur on, ignore_alpha 0.5, match:namespace rofi
layerrule = blur on, match:namespace logout_dialog

