foreground            {{colors.on_background.default.hex}}
background            {{colors.background.default.hex}}
selection_foreground  {{colors.on_primary.default.hex}}
selection_background  {{colors.primary.default.hex}}
url_color             {{colors.primary.default.hex}}

# Active/Inactive tabs
active_tab_foreground   {{colors.on_primary.default.hex}}
active_tab_background   {{colors.primary.default.hex}}
inactive_tab_foreground {{colors.on_surface_variant.default.hex}}
inactive_tab_background {{colors.surface_variant.default.hex}}

# Standard ANSI Colors
color0  {{colors.surface.default.hex}}
color8  {{colors.surface_variant.default.hex}}
color1  {{colors.error.default.hex}}
color9  {{colors.error_container.default.hex}}
color2  {{colors.primary.default.hex}}
color10 {{colors.primary_container.default.hex}}

